set -g mouse on
set -g mode-keys vi
run-shell ~/tmux-resurrect/resurrect.tmux

set -g default-terminal "screen-256color" 
set -g default-terminal "xterm-256color" 
set -g default-terminal "screen.xterm-256color" 
set -g default-terminal "tmux-256color"
